### ISSUE TITLE
Bug while deleting project.

### ISSUE THREAD

**Issue by gsbenevides2** [spckio/spck-issues#59]
First price pardon my english, i am brazilian and i am using Google Translate.
Second after adding File System. There is an error deleting the project in the Android app.
In the logs the following message appears:
```
[10:19:41] Could not find parent for: /data/data/io.spck/files/HTML Seed
```
Version Build: 0.8.1
Version APK:3.0.1

**Comment by spck-io** [comment]
Thank you for the bug report, will look into this.

**Comment by omegapaulo** [comment]
This issue is still going on.

**Comment by spck-io** [comment]
This has been fixed, please update to android app 3.0.3 asap!

**Comment by gsbenevides2** [comment]
Hello I am in the informed version but the error still persisted. 
I am sending images containing the logs and warnings.
![Screenshot_2019-12-18-18-43-21](https://user-images.githubusercontent.com/45762112/71125997-d17b9580-21c6-11ea-9992-a5a022401b4a.png)
![Screenshot_2019-12-18-18-43-29](https://user-images.githubusercontent.com/45762112/71125999-d2142c00-21c6-11ea-88d9-81b074daf21f.png)
![Screenshot_2019-12-18-18-46-42](https://user-images.githubusercontent.com/45762112/71126000-d2142c00-21c6-11ea-9bc1-43541218655c.png)
