### ISSUE TITLE
Can't checkout git

### ISSUE THREAD

**Issue by katuiche** [spckio/spck-issues#68]
Tested in v0.8.3
I have cloned a private gitLab repository with 3 branches but the checkout option only gives me the option to switch to master.
Closing and opening the app made the project disappear.

**Comment by spck-io** [comment]
Thanks for the bug report. Please update the android app to the latest version, and make sure the editor is on version 0.8.5+. That should fix the empty project problem. Will need to investigate the checkout branch problem.

**Comment by katuiche** [comment]
Updated to version 0.8.6 and cleaned data and app cache. Still can't checkout branch.
The problem of disappearing project was fixed.

**Comment by spck-io** [comment]
This issue should now be fixed in editor version 0.9.0 and update Android app version to 3.0.6. There is also new features to add branch locally, and to fetch remote branches manually after updates to the remote branches after cloning.
